language: cpp

os: osx
osx_image: xcode10.2

addons:
  homebrew:
    packages:
      - meson
      - qt
    update: true

script:
  - export PATH="/usr/local/opt/qt/bin:$PATH"
  - meson -Ddemo=true builddir
  - ninja -C builddir

notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGx1Y2ElM0F6M250dS54eXovJTIxeWpCZUJ6WUhrUG50aXNscEpmJTNBbWF0cml4Lm9yZw"
    on_success: never
    on_failure: always
    on_start: never
